# Write your MySQL query statement below
SELECT NAME
FROM EMPLOYEE AS T1
JOIN (SELECT MANAGERID FROM EMPLOYEE 
     GROUP BY MANAGERID
     HAVING COUNT(MANAGERID) >=5)AS T2
     ON T1.ID = T2.MANAGERID