# Write your MySQL query statement below
SELECT PRICES.PRODUCT_ID, ROUND(SUM(PRICES.PRICE*UNITSSOLD.UNITS)/SUM(UNITSSOLD.UNITS),2) as AVERAGE_PRICE
FROM PRICES 
JOIN UNITSSOLD
ON PRICES.PRODUCT_ID = UNITSSOLD.PRODUCT_ID AND (UNITSSOLD.PURCHASE_DATE BETWEEN PRICES.START_DATE AND PRICES.END_DATE)
GROUP BY PRODUCT_ID;
